// Code generated by cue2go. DO NOT EDIT.
// Source: /Users/ripta/projects/utilicue/examples/db
package db

type Title string

// Identity is a record of a person's name.
type Identity struct {
	First  string
	Middle string
	Last   string
	Nick   *string
}

// Person is a record of a person.
type Person struct {
	Title    string
	Name     Identity
	Age      int
	Attrs    any
	Children People
}

// People is a list of person records.
type People []Person
