// Code generated by cue2go. DO NOT EDIT.
// Source: /Users/ripta/projects/utilicue/examples/db

package db

type Identity struct {
	First string
	Middle string
	Last string
	Nick string
}
type Person struct {
	Age int
}
